server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/clients/**
        - id: INVOICE-SERVICE
          uri: lb://INVOICE-SERVICE
          predicates:
            - Path=/invoices/**

eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost



